"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.folderTreeController = exports.settingsController = exports.statusBarController = exports.explorerController = exports.sidebarController = exports.panelController = exports.menuBarController = exports.editorController = exports.activityBarController = void 0;
var tsyringe_1 = require("tsyringe");
var activityBar_1 = require("./activityBar");
var editor_1 = require("./editor");
var explorer_1 = require("./explorer/explorer");
var folderTree_1 = require("./explorer/folderTree");
var menuBar_1 = require("./menuBar");
var panel_1 = require("./panel");
var settings_1 = require("./settings");
var sidebar_1 = require("./sidebar");
var statusBar_1 = require("./statusBar");
exports.activityBarController = tsyringe_1.container.resolve(activityBar_1.ActivityBarController);
exports.editorController = tsyringe_1.container.resolve(editor_1.EditorController);
exports.menuBarController = tsyringe_1.container.resolve(menuBar_1.MenuBarController);
exports.panelController = tsyringe_1.container.resolve(panel_1.PanelController);
exports.sidebarController = tsyringe_1.container.resolve(sidebar_1.SidebarController);
exports.explorerController = tsyringe_1.container.resolve(explorer_1.ExplorerController);
exports.statusBarController = tsyringe_1.container.resolve(statusBar_1.StatusBarController);
exports.settingsController = tsyringe_1.container.resolve(settings_1.SettingsController);
exports.folderTreeController = tsyringe_1.container.resolve(folderTree_1.FolderTreeController);
//# sourceMappingURL=index.js.map