export declare const defaultClassName: string;
export declare const containerClassName: string;
export declare const normalItemsClassName: string;
export declare const globalItemsClassName: string;
export declare const itemClassName: string;
export declare const itemCheckedClassName: string;
export declare const itemDisabledClassName: string;
export declare const labelClassName: string;
export declare const indicatorClassName: string;
