export * from './activityBar';
export * from './editor';
export * from './menuBar';
export * from './notification';
export * from './panel';
export * from './problems';
export * from './settings';
export * from './sidebar';
export * from './statusBar';
export * from './layout';

import { container } from 'tsyringe';
import { ExplorerController } from './explorer/explorer';
import { FolderTreeController } from './explorer/folderTree';
import { SearchController } from './search/search';
import { NotificationController } from './notification';
import { SettingsController } from './settings';
import { ProblemsController } from './problems';
import { MenuBarController } from './menuBar';
export const explorerController = container.resolve(ExplorerController);
export const searchController = container.resolve(SearchController);
export const folderTreeController = container.resolve(FolderTreeController);
export const notificationController = container.resolve(NotificationController);
export const settingController = container.resolve(SettingsController);
export const problemsController = container.resolve(ProblemsController);
export const menuBarController = container.resolve(MenuBarController);
