import { ActivityBarController } from './activityBar';
import { EditorController } from './editor';
import { ExplorerController } from './explorer/explorer';
import { FolderTreeController } from './explorer/folderTree';
import { SearchController } from './search/search';
import { MenuBarController } from './menuBar';
import { NotificationController } from './notification';
import { PanelController } from './panel';
import { SettingsController } from './settings';
import { SidebarController } from './sidebar';
import { StatusBarController } from './statusBar';
import { WorkbenchController } from './workbench';
export declare const activityBarController: ActivityBarController;
export declare const editorController: EditorController;
export declare const menuBarController: MenuBarController;
export declare const panelController: PanelController;
export declare const sidebarController: SidebarController;
export declare const explorerController: ExplorerController;
export declare const searchController: SearchController;
export declare const statusBarController: StatusBarController;
export declare const settingsController: SettingsController;
export declare const folderTreeController: FolderTreeController;
export declare const workbenchController: WorkbenchController;
export declare const notificationController: NotificationController;
